spring:
  application:
    name: bentfores-analysis-service
  liquibase:
    enabled: false
    change-log: classpath:db.changelog/changelog_config.yaml

  jackson:
    default-property-inclusion: NON_EMPTY

  kafka:
    consumer:
      group-id: bentfores-analysis-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      auto-offset-reset: earliest

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false

system:
  kafka:
    topics:
      product-info:
        name: analysis-service.product-info.v1
        protobuf-value-type: com.bentfores.analysis.service.ProductInfo$ProductsInfo

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # отправляет 100% трассировок
    propagation:
      type: b3
  endpoints:
    web:
      exposure:
        include: prometheus, swagger-ui, info, metrics, health, threaddump
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

jobs:
  supplier-info-getter:
    fixed-delay: 30
    initial-delay-in-millis: 30
    enabled: true
    properties:
      thresholdMinutes: 10
      batchSize: 10
  blank-supplier-info-getter:
    fixed-delay: 3600000
    initial-delay-in-millis: 30
    enabled: true
    properties:
      thresholdMinutes: 10
      batchSize: 10

logbook:
  filter:
    enabled: true
  format:
    style: http
  exclude:
    - /swagger-ui/**
    - /actuator/**
    - /openapi/**
    - /index.html
    - /v3/api-docs/**

logging:
  level:
    org.zalando.logbook: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"